# Generated by Django 6.0.6 on 2026-06-18 21:56 喵

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_copyright', models.CharField(default='© 2026 Ariakage 保留所有权利.', max_length=120, verbose_name='页脚版权文案')),
                ('footer_record_text', models.CharField(default='湘ICP备2025108132号-2', max_length=120, verbose_name='备案文案')),
                ('footer_record_url', models.URLField(default='https://beian.miit.gov.cn/', verbose_name='备案链接')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
    ]
