# Generated by Django 6.0.6 on 2026-06-19 07:47 喵

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthLookupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_code', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='识别码')),
                ('sr_user_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='SR 用户 ID')),
                ('nickname', models.CharField(max_length=150, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, max_length=500, verbose_name='头像')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('is_admin', models.BooleanField(default=False, verbose_name='组织管理员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'OAuth 用户查找码',
                'verbose_name_plural': 'OAuth 用户查找码',
            },
        ),
    ]
