# Generated by Django 6.0.6 on 2026-06-19 09:05 喵

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_oauthlookupcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_user_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='SR 用户 ID')),
                ('markdown', models.TextField(blank=True, verbose_name='Bio Markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lookup_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio_profile', to='core.oauthlookupcode', verbose_name='识别码')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联后台用户')),
            ],
            options={
                'verbose_name': '用户 Bio',
                'verbose_name_plural': '用户 Bio',
            },
        ),
    ]
