# Generated by Django 6.0.6 on 2026-06-19 15:40 喵

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bioprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortcutLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('url', models.CharField(max_length=500, verbose_name='链接')),
                ('description', models.CharField(blank=True, max_length=180, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('open_new_tab', models.BooleanField(default=True, verbose_name='新窗口打开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '快捷链接',
                'verbose_name_plural': '快捷链接',
                'ordering': ('sort_order', 'title'),
            },
        ),
    ]
