# Generated by Django 6.0.6 on 2026-06-19 15:55 喵

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shortcutlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=150, verbose_name='手动昵称')),
                ('avatar', models.URLField(blank=True, max_length=500, verbose_name='手动头像')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lookup_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to='core.oauthlookupcode', verbose_name='绑定 OAuth 账号')),
            ],
            options={
                'verbose_name': '成员资料',
                'verbose_name_plural': '成员资料',
                'ordering': ('sort_order', 'nickname', 'id'),
            },
        ),
    ]
