# Generated by Django 6.0.6 on 2026-06-19 16:08 喵

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_memberprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='标题')),
                ('document_url', models.URLField(max_length=800, verbose_name='飞书文档链接')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='简介')),
                ('manual_cover', models.URLField(blank=True, max_length=800, verbose_name='手动头图')),
                ('auto_cover', models.URLField(blank=True, max_length=800, verbose_name='自动头图')),
                ('app_id', models.CharField(blank=True, max_length=120, verbose_name='单独飞书 App ID')),
                ('app_key', models.CharField(blank=True, max_length=240, verbose_name='单独飞书 App Key')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('open_new_tab', models.BooleanField(default=True, verbose_name='新窗口打开')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '飞书文档',
                'verbose_name_plural': '飞书文档',
                'ordering': ('-is_pinned', 'sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='FeishuDocumentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=120, verbose_name='全局飞书 App ID')),
                ('app_key', models.CharField(blank=True, max_length=240, verbose_name='全局飞书 App Key')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '飞书文档配置',
                'verbose_name_plural': '飞书文档配置',
            },
        ),
    ]
