# Generated by Django 6.0.6 on 2026-06-20 喵

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feishudocument_feishudocumentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcutlink',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AlterModelOptions(
            name='shortcutlink',
            options={
                'ordering': ('-is_pinned', 'sort_order', 'title'),
                'verbose_name': '快捷链接',
                'verbose_name_plural': '快捷链接',
            },
        ),
    ]
