# Generated by Django 6.0.6 on 2026-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shortcutlink_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='home_dashboard_description',
            field=models.CharField(default='集中管理团队成员、快捷链接与协作资料。', max_length=180, verbose_name='首页 Dashboard 说明'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_link_url',
            field=models.CharField(default='/', max_length=500, verbose_name='导航跳转地址'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_logo_url',
            field=models.CharField(default='/static/images/logo.png', max_length=500, verbose_name='导航 Logo 地址'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='SR思锐', max_length=80, verbose_name='网站名称'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='support_email',
            field=models.EmailField(default='support@sr-studio.cn', max_length=254, verbose_name='支持邮箱'),
        ),
    ]
