# Generated by Django 6.0.6 on 2026-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesetting_home_dashboard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='sr_user_id_label',
            field=models.CharField(default='SR 用户 ID', max_length=60, verbose_name='SR 用户 ID 字样'),
        ),
    ]
