# Generated by Django 6.0.6 on 2026-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_sr_user_id_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='website_visit_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='网站访问次数'),
        ),
    ]
