# Generated by Django 6.0.6 on 2026-06-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesetting_website_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='lucide_cdn_url',
            field=models.URLField(default='https://unpkg.com/lucide@latest', max_length=500, verbose_name='Lucide CDN 链接'),
        ),
    ]
