# Generated by Django 6.0.6 on 2026-06-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesetting_lucide_cdn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='sweetalert2_cdn_url',
            field=models.URLField(default='https://cdn.jsdelivr.net/npm/sweetalert2@11', max_length=500, verbose_name='SweetAlert2 CDN 链接'),
        ),
    ]
